#tomcat
server.port=8080

# PROFILES
spring.profiles.active=dev


spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.html
#json
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.joda-date-time-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8